config/routes.rb
Rails.application.routes.draw do
  resources :stories

  root 'welcome#index'

  get 'showstory' => 'welcome#showstory'

  get 'userinput' => 'welcome#userinput'

  post 'results' => 'welcome#results'

end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
    

  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :section1, :word1type, :section2, :word2type, :section3, :word3type, :section4)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@stories = Story.all
  	# @selectedtitle = Story.title
  end

  def showstory
    @stories = Story.all
  end

  def userinput
  	@stories = Story.all
    @title = params[:title]
  	@firstword = params[:firstword]
  	@secondword = params[:secondword]
  	@thirdword = params[:thirdword]
  end

  def results
    @stories = Story.all
    @title = params[:title]
    @firstword = params[:firstword]
    @secondword = params[:secondword]
    @thirdword = params[:thirdword]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
	<!DOCTYPE html>
<html>
<head>
  <title>Madlibs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :section1 %><br>
    <%= f.text_area :section1 %>
  </div>
  <div class="field">
    <%= f.label :word1type %><br>
    <%= f.text_field :word1type %>
  </div>
  <div class="field">
    <%= f.label :section2 %><br>
    <%= f.text_area :section2 %>
  </div>
  <div class="field">
    <%= f.label :word2type %><br>
    <%= f.text_field :word2type %>
  </div>
  <div class="field">
    <%= f.label :section3 %><br>
    <%= f.text_area :section3 %>
  </div>
  <div class="field">
    <%= f.label :word3type %><br>
    <%= f.text_field :word3type %>
  </div>
  <div class="field">
    <%= f.label :section4 %><br>
    <%= f.text_area :section4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %>


<center>
<h1>Our Current Archive of User Generated Stories</h1>
    

<div class="row">
  <div id="btn-add">
                <%= link_to new_story_path, class: "btn btn-primary" do %>
                  <span class="glyphicon glyphicon-plus"></span>Create a Template
                <% end %>
              </div>

              <div id="btn-play">
                <%= link_to showstory_path, class: "btn btn-primary" do %>
                  <span class="glyphicon glyphicon-plus"></span>Play
                <% end %>
              </div>
    <% @stories.each do |story| %>
      <div class="col-md-12">

       <div class="panel panel-default">

        <div class="panel-body">
              

         <u><h3><%= story.title %></h3></u>
        
         <p> <%= story.section1 %> [insert <%=story.word1type %>] <%=story.section2%> [insert <%=story.word2type%>] <%=story.section3%> [insert <%=story.word3type%>] <%=story.section4%></p>
       
         <div class="btn-group">
            <%= link_to 'Show', story, class: "btn btn-default" %>
            <%= link_to 'Edit', edit_story_path(story), class: "btn btn-default" %>
            <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Create New Story', new_story_path, class: "btn btn-primary" %>
</center>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Section1:</strong>
  <%= @story.section1 %>
</p>

<p>
  <strong>Word1type:</strong>
  <%= @story.word1type %>
</p>

<p>
  <strong>Section2:</strong>
  <%= @story.section2 %>
</p>

<p>
  <strong>Word2type:</strong>
  <%= @story.word2type %>
</p>

<p>
  <strong>Section3:</strong>
  <%= @story.section3 %>
</p>

<p>
  <strong>Word3type:</strong>
  <%= @story.word3type %>
</p>


<p>
  <strong>Section4:</strong>
  <%= @story.section4 %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/welcome/index.html.erb
<br>



		<div id="btn-add1">
			<%= link_to new_story_path, class: "btn btn-primary" do %>
			  <span class="glyphicon glyphicon-plus"></span>Create a Template
			<% end %>
		</div>
		<div id="btn-play1">
			<%= link_to showstory_path, class: "btn btn-primary" do %>
			  <span class="glyphicon glyphicon-plus"></span>Play
			<% end %>
		</div>

<center>
<h1>Welcome to Madlibs</h1>
<h3>The game where you can create new stories over and over again</h3>
<h2>___________________________</h2>
</center>
<br>

<h3>What would you like to do first? Click on one of the options below: </h3>

<ul>
	<li><%= link_to "Create your Own Game Board Story", stories_path %> <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></li>
	<li>Play the Madlibs Game! Begin by clicking on an available story title below.</li>
		<% @stories.each do |story| %>

			<ul>
				<li><%= link_to "#{story.title}", controller: "welcome",  action: "userinput", title: "#{story.title}"  %></li>
			</ul>
		<% end %>

</ul>
	

		

app/views/welcome/results.html.erb
<h1>Your Story!</h1>
<div class="col-md-12">

       <div class="panel panel-default">

        <div class="panel-body">


<% @stories.each do |story| %>
    <% if story.title == @title %>
        <u><h2><%= story.title %></h2></u>
        <p><%= story.section1 %> <span class="userword"><%= @firstword %></span> <%=story.section2 %> <span class="userword"><%= @secondword %></span> <%=story.section3%> <span class="userword"><%= @thirdword%></span> <%= story.section4 %></p>

    <% end %>
<% end %>
</div>
</div>
</div>

app/views/welcome/showstory.html.erb
<h1>Select Your Story to Play!</h1>
<p>Select a story of your choice from the list below to beging playing:</p>

<% @stories.each do |story| %>

	<ul>
		<li><%= link_to "#{story.title}", controller: "welcome",  action: "userinput", title: "#{story.title}"  %></li>
	</ul>
<% end %>

app/views/welcome/userinput.html.erb
<h1>Adding your words</h1>
<p>Let select the words that will be in your story.</p>

<h3>Title: <%= @title %></h3>



<% @stories.each do |story| %>
  <% if story.title == @title %>
   <%= form_tag '/results', method: "post" do %>
        <%= story.word1type %> <input style="color: black" type="string" name="firstword" value="" color="black"><br> 
        <%= story.word2type %> <input style="color: black" type="string" name="secondword" value="" color="black"><br>
        <%= story.word3type %> <input style="color: black" type="string" name="thirdword" value="" color="black"><br>
        <input type="hidden" name="title" value = "<%= @title %>" ><br> 
        <%= submit_tag "Write my story" , style: "color: black;" %>
    <% end %>
    <% end %>
<% end %>

<%= link_to "Return to Home Menu", root_path %>